# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

include:
  - path: ./nvidia-nemotron-nano-9b-v2/compose.yml
  - path: ./cosmos3-reasoner/compose.yml
